# Gradle build optimizations & configuration caching
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096m -XX:+UseG1GC -XX:MaxMetaspaceSize=1024m

# AndroidX & Jetpack Compose
android.useAndroidX=true
android.nonTransitiveRclass=true

# Incremental KSP & Kotlin
ksp.incremental=true
kotlin.code.style=official
